[model]

# DivNet "fast" default settings:
# em_iter = 6
# em_burn = 3
# mc_iter = 500
# mc_burn = 250
# stepsize = 0.01
# perturbation = 0.05
# replicates = 5
# base_taxa = 0

# DivNet "careful" default settings:
# em_iter = 10
# em_burn = 5
# mc_iter = 1000
# mc_burn = 500
# stepsize = 0.01
# perturbation = 0.05
# replicates = 5
# base_taxa = 0

# Number of expectation maximization (EM) iterations
em_iter = 6

# Number of EM iterations to burn (i.e., throw out). Unlike mc_burn, this does
# NOT have to be em_iter / 2.
em_burn = 3

# Number of Monte-Carlo (MC) iterations.  Must be even (see mc_burn for
# details).
mc_iter = 500

# Number of MC iterations to burn. It must be mc_iter / 2.  If not, the program
# will abort.
mc_burn = 250

# Variance used for MH samples
stepsize = 0.01

# Perterbation magnitude for zero values when calculating logratios. (Any zero
# value will be replaced with this.) 
perturbation = 0.05

# Number of bootstrap iterations for estimating the variance.
replicates = 5

# The "base" taxa to use in the logratios.  The number represents the (0-based)
# index of the taxon you want.  So 0 here means the first taxon, 1 means the
# second, and so on.  Ideally it is a taxa observed in all samples.  That's not
# likely though, so try a couple of highly abundant taxa to confirm the results
# are robust to the taxon choice. 
base_taxa = 0

[io]
# If you use relative paths here, they will be interpreted relative to the
# directory from which you run the divnet-rs command.  If things get weird with
# that, or you're using a job scheduler like slurm or torque, just specify the
# absolute path here instead.

# The path to your count/asv/otu table
count_table = "/home/ltibbs/divnet-rs/tardigrade_data/full_otu_divnetrs.csv"

# The path to your sample data
sample_data = "/home/ltibbs/divnet-rs/tardigrade_data/full_samdata_divnetrs.csv"

# The path to the file that divnet-rs will generate
output = "/home/ltibbs/divnet-rs/tardigrade_data/full_divnet_output.csv"

[misc]
# An unsigned 64 bit integer used to seed the random number generator.
random_seed = 734095
